### ISSUE TITLE
Customized cluster widgets

### ISSUE THREAD

**Issue by projectatrts** [rorystephenson/flutter_map_supercluster#16]
How do i make a customized cluster widgets that show a summary of their contained Markers as shown in your medium article?

**Comment by serena7889** [comment]
I'm also trying to figure this out. I've extended the Marker class and have a score for each marker, so want to show the marker with the highest score in the cluster. Any advice on how to achieve this would be greatly appreciated!

**Comment by rorystephenson** [comment]
I've added [an example](https://github.com/rorystephenson/flutter_map_supercluster/blob/master/example/lib/custom_cluster_marker_page.dart) which demonstrates how you can customise the cluster Marker based on what it contains.

The core idea is to:

1.  [Add a clusterDataExtractor](https://github.com/rorystephenson/flutter_map_supercluster/blob/40cd9cc7f5c7b1a83eb91a9ef013e4535da34cac/example/lib/custom_cluster_marker_page.dart#L48-L49) which extracts the data you need for the cluster from a Marker (or your custom extension of Marker) and [defines how this extracted data should be 'combined'](https://github.com/rorystephenson/flutter_map_supercluster/blob/40cd9cc7f5c7b1a83eb91a9ef013e4535da34cac/example/lib/custom_cluster_marker_page.dart#L80-L84) when markers become part of a cluster and when clusters are joined (this happens during the calculation of clusters).
2. Use the extracted cluster data [in your cluster widget builder](https://github.com/rorystephenson/flutter_map_supercluster/blob/40cd9cc7f5c7b1a83eb91a9ef013e4535da34cac/example/lib/custom_cluster_marker_page.dart#L54).

This will be much more efficient if you avoid holding on to references of all of the contained markers or build up a long list of data in your custom cluster data. For example in your case @serena7889 if you want to show the highest score of the contained Markers in the cluster widget it will be much more efficient to just save the highest score value in your custom cluster data instead of a list of all of the marker scores contained in the cluster.

If my explanation is not clear don't hesitate to ask more.

**Comment by serena7889** [comment]
Hi Rory, thank you very much for taking the time to respond and add the example! This looks great, and I look forward to implementing it in the way you suggested.
