### ISSUE TITLE
computeSize option missing?

### ISSUE THREAD

**Issue by aqrc** [rorystephenson/flutter_map_supercluster#3]
There are following lines in `SuperclusterLayer`:
```  
/// Implement this function to extract extra data from Markers which can be
/// used in the [builder] and [computeSize].
final ClusterDataBase Function(Marker marker)? clusterDataExtractor;
```
But I can't find this `computeSize` thing anywhere. 

As I understand it should allow computing `clusterWidgetSize` for each cluster instead of having constant one.

So could you please explain what `computeSize` is and how to use it?

**Comment by rorystephenson** [comment]
Hi @aqrc this is a documentation error, my apologies. `clusterWidgetSize` is always fixed and making it variable would be non-trivial since we need to know the maximum visual size of clusters to determine the search boundary otherwise clusters would disappear near the edges of the screen if the point of the cluster is outside of the current map boundary but the size of the cluster widget makes is partially visible.

The mention of `computeSize` is a copy-paste error from the `supercluster` package which powers this package. In `supercluster` `computeSize` allows you to disable the computation of the size of a cluster if so-desired which allows less calculations to be made when clustering. This optional is not available in `flutter_map_supercluster` because the assumption is made that the number of markers in a cluster will always want to be shown (or at least used to modify the appearance of the cluster widget). I will remove this incorrect reference in the next version.

**Comment by rorystephenson** [comment]
The latest version has been published with the fixed documentation.
