### ISSUE TITLE
Controller replaceAll() throws error 

### ISSUE THREAD

**Issue by tratteo** [rorystephenson/flutter_map_supercluster#8]
When using the `SuperclusterMutableController` method `replaceAll()`, the following error is thrown and the markers are not shown.

<img width="1271" alt="image" src="https://github.com/rorystephenson/flutter_map_supercluster/assets/31132987/8cd32ab9-5fdb-471e-a974-7fd4c92fa5c2">

**Comment by rorystephenson** [comment]
@tratteo It looks like dart doesn't like something that is being sent to another isolate. If you don't have too many markers try suggestion number 2 here: https://github.com/rorystephenson/flutter_map_supercluster/issues/2#issuecomment-1519031583 .

Otherwise it's a case of figuring out what dart doesn't like about your Markers or clusterDataExtractor.

**Comment by rorystephenson** [comment]
@tratteo note that the newest release 4.0.0 simplifies configuring the map to use isolates or not. See the docs for IndexBuilders. I'm closing this now but if your problem persists let me know.
